### ISSUE TITLE
Assetic error in Symfony 2.7

### ISSUE THREAD

**Issue by foaly-nr1** [8p/EightPointsGuzzleBundle#20] opened 2015-09-03 11:18 UTC
When warming up the cache, assetic is throwing the following error:
`assetic.ERROR: The template "GuzzleBundle::profiler.html.twig" contains an error: The function "dump" does not exist in "GuzzleBundle::profiler.html.twig" at line 47`

This is because dump was introduced in added in Twig 1.5 and [Symfony 2.7 seems to be using Twig 1.2](https://github.com/symfony/TwigBridge/blob/11f782ad6f7971ebc9b461e5cbf7f70c1c332158/composer.json).

**Comment by florianpreusner** [comment] 2015-09-10 07:40
Hi,

sorry for this late reply. Symfony 2.7.0 requires twig ~1.18. The bridge (posted link) requires ~1.20. Both versions are higher than 1.5. I'm not able to reproduce this error. Can you check which version of twig is installed by looking into composer.lock?

Best regards
Florian

**Comment by mlebkowski** [comment] 2015-11-17 16:46
I have the same issue in my production environment. Symfony `v2.6.10`, Twig `v1.18.2`, GuzzleBundle `v4.2.1`.

This is because twig only loads the debug extension (with `dump` function) in debug mode. Run this with empty cache (`rm -fr app/cache/prod`) to confirm:

```
app/console assetic:dump --no-debug --env=prod
```

**Comment by sebastianblum** [comment] 2016-02-02 21:25
The problem is, that the method Dump is only available in environments with enabled debug.

So in production, the dump method is not available.

**Comment by florianpreusner** [comment] 2016-02-02 22:28
Yes, this could be a solution!

**Comment by asprega** [comment] 2016-07-22 13:24
Reviving this thread: I wonder what's the point of having debug stuff available when you're warming up a non-debug cache. Couldn't we just "exclude" that when the kernel debug flag is set to false?

**Comment by gregurco** [comment] 2017-12-04 13:49
@foaly-nr1 @mlebkowski @sebastianblum @asprega fixed in PR #164

**Closed by gregurco** 2017-12-04 13:49 UTC
Labels: bug

**Comment by florianpreusner** [comment] 2018-01-15 10:06
Released in v7.3.0 (https://github.com/8p/EightPointsGuzzleBundle/releases/tag/7.3.0)
