### ISSUE TITLE
Invalid definition for service "eight_points_guzzle.handler_stack.xyz"

### ISSUE THREAD

**Issue by skroberto** [8p/EightPointsGuzzleBundle#286] opened 2019-12-18 16:40 UTC
| Q                | A
| ---------------- | -----
| Symfony version  | 4.4.0
| Bundle version   | 7.6.0
| PHP version   | 7.1.21
| Guzzle version   | 6.3.3

Hi, not sure if this is a bug in the bundle or a misconfiguration on my side so please help me to track this down.

Symfony 4.4 has introduced a Service Container Linter to check the services defined in the container. This can be run from console: `./bin/console lint:container -vvv`

My linter is failing with this error
```
[Symfony\Component\DependencyInjection\Exception\InvalidParameterTypeException]
Invalid definition for service "eight_points_guzzle.handler_stack.xyz": argument 1 of "GuzzleHttp\HandlerStack::push" accepts "callable", "Symfony\Component\ExpressionLanguage\Expression" passed.
```

My yaml configuration looks like:

```
parameters:
    eight_points_guzzle.symfony_log_formatter.pattern: ">>>>>>>>\n{request}\n<<<<<<<<\n{response}\n--------\n{error}"

eight_points_guzzle:
    clients:
        xyz:
            base_url: "%xyz_api_url%"
            options:
                timeout: 30
                http_errors: true
                headers: []
            plugin: null

```

**Comment by gregurco** [comment] 2020-01-19 19:12
Hello @skroberto 
No, the problem is not in misconfiguration. I check your config and it seeks to be ok. Probably you have the same issue as in #288 because I didn't manage to receive your error message, but with SF4.4 I received same message as for SF5.0. I think the problem is in linter. It can't handle all cases for now.
Can you provide information, if bundle works or doesn't work properly? Do you have any issues with requests via guzzle bundle or everything is ok? It will help us to understand the problem.

**Comment by knyk** [comment] 2020-01-20 10:12
@skroberto this error is related to symfony. it had bug where linter couldn't resolve services defined by using expression language. it is already fixed by one of the latest symfony versions

**Closed** 2020-01-20 10:13 UTC
